language: php

sudo: false

services:
  - docker

php:
  - 7.2
  - 7.3

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - |
    if [[ -z $COMPOSER_FLAGS ]]; then
      composer run test
    else
      composer run phpstan:test
      composer run ecs:test
      composer run phpunit:test
      composer run insights -- --disable-security-check
    fi
  - rm -rf vendor/
  - composer install --no-dev
  - composer run insights -- --disable-security-check
jobs:
  include:
    - stage: build docker image
      if: tag IS present
      php: 7.3
      env: COMPOSER_FLAGS=""
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - export REPO=$DOCKER_USERNAME/phpinsights
        - docker build -f docker/Dockerfile -t $REPO:$TRAVIS_TAG .
        - docker tag $REPO:$TRAVIS_TAG $REPO:latest
        - docker push $REPO
